[package]
name = "cds2seq"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { workspace = true }
either = "1.11.0"
