[package]
name = "cds2seq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
dbg_hex = "0.2.0"
either = "1.11.0"
