[package]
name = "vagsanitizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { workspace = true }

[dev-dependencies]
md5 = "0.7.0"
